Repository Hybris95/UEX-Trader, pull requests merged in 2025-01, with the labels that each got.

#235 feat: add a SQLite Cache solution for API cache persistence
  _internal/translations.ini
  api.py
  cache_manager.py
  config_manager.py
  config_tab.py
  conftest.py
  requirements.txt
  test_sqlcache.py
Labels: enhancement

#240 r0.6.0-1
  README.md
  _internal/translations.ini
  api.py
  best_trade_route.py
  cache_manager.py
  config_manager.py
  config_tab.py
  trade_route_tab.py
  translation_manager.py
Labels: bug, enhancement

#241 Feat/cache manager
  _internal/translations.ini
  api.py
  cache_manager.py
  config_manager.py
  config_tab.py
  conftest.py
  requirements.txt
  test_sqlcache.py
Labels: enhancement

#242 feat: Uses a new global_variables file to store some global values, u…
  README.md
  cache_manager.py
  config_manager.py
  global_variables.py
Labels: enhancement, internal

#244 feat: Add extensive unitary tests + a functional test for caching
  test_sqlcache.py
Labels: enhancement, internal

#246 feat: Split data when recovered from API into several cache keys
  api.py
  best_trade_route.py
  cache_manager.py
  gui.py
  trade_route_tab.py
  trade_tab.py
Labels: enhancement, internal

#251 feat: Add a splashscreen for GUI initialization
  .github/workflows/python-app.yml
  _internal/resources/UEXTrader_splashscreen.png
  gui.py
Labels: enhancement

#252 d0.6.1-2
  .github/workflows/python-app.yml
  _internal/resources/UEXTrader_splashscreen.png
  api.py
  best_trade_route.py
  cache_manager.py
  gui.py
  trade_route_tab.py
  trade_tab.py
Labels: enhancement, internal

#255 d0.6.1-3
  gui.py
Labels: bug

#256 n0.6.1-1
  .github/workflows/python-app.yml
  README.md
  _internal/resources/UEXTrader_splashscreen.png
  _internal/translations.ini
  api.py
  best_trade_route.py
  cache_manager.py
  config_manager.py
  config_tab.py
  conftest.py
  global_variables.py
  gui.py
  requirements.txt
  test_sqlcache.py
  trade_route_tab.py
  trade_tab.py
Labels: bug, enhancement, internal

#257 Feat/new commodity submit
  _internal/translations.ini
  api.py
  commodity.py
  global_variables.py
  gui.py
  submit_tab.py
  test_config_manager.py
  test_sqlcache.py
  test_uexcorp_trader.py
Labels: enhancement

#260 feat: Load single values from cache if available instead of filtering…
  api.py
  global_variables.py
Labels: enhancement, internal

#261 feat: Replace Cache - Initial Version
  api.py
  cache_manager.py
Labels: enhancement, internal

#272 feat: Add clean_cache capacity from a given TTL for both Dict and SQL…
  api.py
  cache_manager.py
  global_variables.py
  gui.py
Labels: enhancement, internal

#273 Feat/metrics initial
  api.py
  best_trade_route.py
  cache_manager.py
  config_manager.py
  config_tab.py
  global_variables.py
  gui.py
  metrics.db
  metrics.py
  metrics_widget.py
  submit_tab.py
  trade_route_tab.py
  trade_tab.py
  translation_manager.py
Labels: enhancement, internal, performance

#277 feat: Add action buttons only on final display
  best_trade_route.py
  metrics.py
Labels: performance

#278 fix: Revert batch inserts for metrics and add error management in SQL…
  cache_manager.py
  metrics.py
Labels: bug, internal, performance

#282 feat: Rework get/set in cache, load cache on startup only if unavailable
  .github/workflows/python-app.yml
  api.py
  cache_manager.py
  config_manager.py
  global_variables.py
  gui.py
  test_sqlcache.py
Labels: enhancement, internal

#281 d0.6.1-5
  .github/workflows/python-app.yml
  api.py
  best_trade_route.py
  cache_manager.py
  config_manager.py
  config_tab.py
  global_variables.py
  gui.py
  metrics.db
  metrics.py
  metrics_widget.py
  submit_tab.py
  test_sqlcache.py
  trade_route_tab.py
  trade_tab.py
  translation_manager.py
Labels: bug, enhancement, internal, performance

#283 n0.6.1-3
  .github/workflows/python-app.yml
  api.py
  best_trade_route.py
  cache_manager.py
  config_manager.py
  config_tab.py
  global_variables.py
  gui.py
  metrics.db
  metrics.py
  metrics_widget.py
  submit_tab.py
  test_sqlcache.py
  trade_route_tab.py
  trade_tab.py
  translation_manager.py
Labels: bug, enhancement, internal, performance

#284 r0.6.1-1
  .github/workflows/python-app.yml
  README.md
  _internal/resources/UEXTrader_splashscreen.png
  _internal/translations.ini
  api.py
  best_trade_route.py
  cache_manager.py
  commodity.py
  config_manager.py
  config_tab.py
  conftest.py
  global_variables.py
  gui.py
  metrics.db
  metrics.py
  metrics_widget.py
  requirements.txt
  submit_tab.py
  test_config_manager.py
  test_sqlcache.py
  test_uexcorp_trader.py
  trade_route_tab.py
  trade_tab.py
  translation_manager.py
Labels: bug, enhancement, internal, performance

#288 fix: Optimize calculate_trade_routes_rework, disable distance features
  best_trade_route.py
  global_variables.py
  gui.py
  tools.py
Labels: performance

#289 d0.6.1-6
  best_trade_route.py
  global_variables.py
  gui.py
  tools.py
Labels: performance

#290 n0.6.1-4
  best_trade_route.py
  global_variables.py
  gui.py
  tools.py
Labels: performance

#291 r0.6.1-2
  best_trade_route.py
  global_variables.py
  gui.py
  tools.py
Labels: performance

#292 v0.6.1
  .github/workflows/python-app.yml
  README.md
  _internal/resources/UEXTrader_splashscreen.png
  _internal/translations.ini
  api.py
  best_trade_route.py
  cache_manager.py
  commodity.py
  config_manager.py
  config_tab.py
  conftest.py
  global_variables.py
  gui.py
  metrics.db
  metrics.py
  metrics_widget.py
  requirements.txt
  submit_tab.py
  test_config_manager.py
  test_sqlcache.py
  test_uexcorp_trader.py
  tools.py
  trade_route_tab.py
  trade_tab.py
  translation_manager.py
Labels: bug, enhancement, internal, performance

#293 feat(python-app.yml): Remove python version and add commit sha instead
  .github/workflows/python-app.yml
Labels: enhancement

#295 feat: Add Storage pre-requisites, fixes an issue with method to conta…
  README.md
  cache_manager.py
Labels: bug, documentation

#296 feat: Implement Cache Cleanup after having data loaded
  global_variables.py
  gui.py
Labels: enhancement
